### ISSUE TITLE
Make footer customizable from the config file

### ISSUE THREAD

**Issue by mikeanth-dev** [mikeanth-dev/hugo-coder#3]
There should be an entry in the config file, exposing some footer configuration, such as:

``` yml
footer:
  enabled: true / false # show / hide footer
  copyright:
    enabled: true / false # show / hide copyright notice
    since: 2022 # if enabled, the start year
  credits:
    enabled: true / false # show / hide 'Powered by...'
```
