### ISSUE TITLE
Add CTA on Home Page

### ISSUE THREAD

**Issue by mikeanth-dev** [mikeanth-dev/hugo-coder#8]
The home page should have a big and obvious call to action to `Contact Me` or `About Me`, something to prompt the user to a next immediate action.

Could be something as simple as:

``` yml
cta:
  text: Contact pe
  link: <url>/contact
```
